'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class setting extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  setting.init({
    title: DataTypes.STRING,
    logo: DataTypes.STRING,
    favicon: DataTypes.STRING,
    loader: DataTypes.STRING,
    is_loader: DataTypes.INTEGER,
    feature_image: DataTypes.STRING,
    primary_color: DataTypes.STRING,
    smtp_check: DataTypes.INTEGER,
    email_host: DataTypes.STRING,
    email_port: DataTypes.STRING,
    email_encryption: DataTypes.STRING,
    email_user: DataTypes.STRING,
    email_pass: DataTypes.STRING,
    email_from: DataTypes.STRING,
    email_from_name: DataTypes.STRING,
    contact_email: DataTypes.STRING,
    version: DataTypes.STRING,
    overlay: DataTypes.TEXT,
    google_analytics_id: DataTypes.STRING,
    meta_keywords: DataTypes.TEXT,
    meta_description: DataTypes.TEXT,
    is_shop: DataTypes.INTEGER,
    is_blog: DataTypes.INTEGER,
    is_faq: DataTypes.INTEGER,
    is_contact: DataTypes.INTEGER,
    facebook_check: DataTypes.INTEGER,
    facebook_client_id: DataTypes.STRING,
    facebook_client_secret: DataTypes.STRING,
    facebook_redirect: DataTypes.STRING,
    google_check: DataTypes.INTEGER,
    google_client_id: DataTypes.STRING,
    google_client_secret: DataTypes.STRING,
    google_redirect: DataTypes.STRING,
    min_price: DataTypes.DOUBLE,
    max_price: DataTypes.DOUBLE,
    footer_phone: DataTypes.STRING,
    footer_address: DataTypes.TEXT,
    footer_email: DataTypes.STRING,
    footer_gateway_img: DataTypes.STRING,
    social_link: DataTypes.TEXT,
    friday_start: DataTypes.STRING,
    friday_end: DataTypes.STRING,
    saturday_start: DataTypes.STRING,
    saturday_end: DataTypes.STRING,
    copy_right: DataTypes.STRING,
    is_slider: DataTypes.INTEGER,
    is_category: DataTypes.INTEGER,
    is_product: DataTypes.INTEGER,
    is_top_banner: DataTypes.INTEGER,
    is_recent: DataTypes.INTEGER,
    is_top: DataTypes.INTEGER,
    is_best: DataTypes.INTEGER,
    is_flash: DataTypes.INTEGER,
    is_brand: DataTypes.INTEGER,
    is_blogs: DataTypes.INTEGER,
    is_campaign: DataTypes.INTEGER,
    is_brands: DataTypes.INTEGER,
    is_bottom_banner: DataTypes.INTEGER,
    is_service: DataTypes.INTEGER,
    campaign_title: DataTypes.STRING,
    campaign_end_date: DataTypes.STRING,
    campaign_status: DataTypes.INTEGER,
    twilio_sid: DataTypes.STRING,
    twilio_token: DataTypes.STRING,
    twilio_form_number: DataTypes.STRING,
    twilio_country_code: DataTypes.STRING,
    is_announcement: DataTypes.INTEGER,
    announcement: DataTypes.STRING,
    announcement_delay: DataTypes.DOUBLE,
    is_maintenance: DataTypes.INTEGER,
    maintenance_image: DataTypes.STRING,
    maintenance_text: DataTypes.TEXT,
    is_twilio: DataTypes.INTEGER,
    twilio_section: DataTypes.TEXT,
    is_three_c_b_first: DataTypes.INTEGER,
    is_popular_category: DataTypes.INTEGER,
    is_three_c_b_second: DataTypes.INTEGER,
    is_highlighted: DataTypes.INTEGER,
    is_two_column_category: DataTypes.INTEGER,
    is_popular_brand: DataTypes.INTEGER,
    is_featured_category: DataTypes.INTEGER,
    is_two_c_b: DataTypes.INTEGER,
    theme: DataTypes.STRING,
    google_recaptcha_site_key: DataTypes.STRING,
    google_recaptcha_secret_key: DataTypes.STRING,
    recaptcha: DataTypes.INTEGER,
    currency_direction: DataTypes.INTEGER,
    google_analytics: DataTypes.TEXT,
    google_adsense: DataTypes.TEXT,
    facebook_pixel: DataTypes.TEXT,
    facebook_messenger: DataTypes.TEXT,
    is_google_analytics: DataTypes.INTEGER,
    is_google_adsense: DataTypes.INTEGER,
    is_facebook_pixel: DataTypes.INTEGER,
    is_facebook_messenger: DataTypes.INTEGER,
    announcement_link: DataTypes.TEXT,
    is_attribute_search: DataTypes.INTEGER,
    is_range_search: DataTypes.INTEGER,
    view_product: DataTypes.INTEGER,
    home_page_title: DataTypes.STRING,
    is_privacy_terms: DataTypes.INTEGER,
    policy_link: DataTypes.STRING,
    terms_link: DataTypes.STRING,
    is_guest_checkout: DataTypes.INTEGER,
    custom_css: DataTypes.TEXT,
    announcement_title: DataTypes.STRING,
    announcement_type: DataTypes.STRING,
    is_cookie: DataTypes.INTEGER,
    cookie_text: DataTypes.STRING,
    announcement_details: DataTypes.TEXT,
    decimal_separator: DataTypes.STRING,
    thousand_separator: DataTypes.STRING,
    disqus: DataTypes.TEXT,
    is_disqus: DataTypes.INTEGER,
    is_decimal: DataTypes.INTEGER
  }, {
    sequelize,
    modelName: 'setting',
  });
  return setting;
};